from Linked_List.singly_linked_list import SinglyLinkedList

list = SinglyLinkedList()
list.singl_append(35)
list.singl_append(23)
list.singl_append(11)
list.singl_printlist()
list.singl_delete(23)
list.singl_printlist()
list.singl_delete_at(1)
list.singl_printlist()
list.singl_prepend(12)
list.singl_printlist()
list.singl_insert_after(11, 1)
list.singl_printlist()
list.singl_update(2 , 5)
list.singl_printlist()